server:
  port: 1205
  servlet:
    context-path: "/banking"

spring:
  datasource:
    url: "jdbc:mysql://localhost/banking"
    username: "root"
    password: "root"
  sql:
    init:
      mode: ALWAYS
  jpa:
    properties:
      hibernate.format_sql: true
    show-sql: true
    hibernate:
      ddl-auto: update

upload:
  file:
    name: "profile-pictures/"


